Highlight all task instances across the graph on focus
shadanan/yotei pull request #33
Opened 2024-07-09 22:00 UTC by sachiesharma

Add a highlight feature on mouseover that also highlights the same node across the data

https://github.com/shadanan/yotei/assets/361429/d9405fb6-046e-4ebb-97e1-f63e5b7a21f2

2024-07-09 22:03 UTC, shadanan requested changes

2024-07-09 22:03 UTC, shadanan commented on frontend/src/lib/DagTable/row.svelte
> +  let highlighted = false;
This variable is not used. You can remove it.

2024-07-09 22:03 UTC, shadanan commented on frontend/src/lib/dndtask.js
Remove this file.

2024-07-09 22:03 UTC, shadanan commented on frontend/src/lib/sachie.svelte
Remove this file.

2024-07-09 23:57 UTC, shadanan approved these changes
Good work. Ship it.

2024-07-10 00:07 UTC, sachiesharma commented on frontend/src/lib/DagTable/row.svelte
> +  // validate relationship
Thanks Kyle! Great to meet you too, I hope we can meet in person in August.

2024-07-10 00:09 UTC, merged